import { sortByNameForDigest } from "./stable-order.js";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import type { AppConfig } from "./config.js";

const execFileAsync = promisify(execFile);

/**
 * The agent's own memory, brought inside the transaction.
 *
 * Codex keeps a turn's conversation in `$CODEX_HOME`: a date-partitioned rollout JSONL plus a
 * sqlite state file and its write-ahead log. The stock kit bind-mounts ONE such directory,
 * read-write, into every agent's container, which has two consequences it never intended. A
 * discarded turn still advances the model's memory, so the agent goes on believing it did the
 * thing that was rolled back; and a turn can write into the directory every OTHER agent on the
 * platform reads next, which is a cross-agent channel with no policy in front of it.
 *
 * Both are closed the same way. Each agent gets its own directory. The turn never mounts that
 * directory: it mounts a per-turn copy, so the real one is not reachable from inside the container
 * at all. On commit the copy is promoted; on any other verdict it is dropped and the real one is
 * restored from a snapshot taken beside it. Spike B measured the result on real `codex exec` turns
 * against a model endpoint that logged every upstream request body: after the restore, call three's
 * conversation history is byte-identical to call one's plus the new question, and
 * `codex exec resume <threadId>` still works.
 *
 * The unit is the whole directory. The sqlite WAL was 852 KB after three turns in that spike, so a
 * snapshot that skipped it would restore a database that still remembers the discarded turn.
 */

export interface SealedCodexHome {
  agentId: string;
  realPath: string;
  /** the copy the container mounts at /codex-home, and the only one the turn can write */
  livePath: string;
  /** the snapshot the restore reads from; never mounted, so the turn cannot reach it */
  prePath: string;
  preDigest: string;
  preFiles: number;
}

export interface CodexHomeDiff {
  added: string[];
  modified: string[];
  removed: string[];
  changed: number;
  truncated: boolean;
}

const DIFF_LIST_LIMIT = 40;

/**
 * The directory name for an agent, which is a path component built from an id the caller supplies.
 * The dot is NOT in the allowed set: with it, an id of ".." sanitises to ".." and the per-agent
 * directory becomes the codex-home root itself, which is the shared-mount hole this whole module
 * exists to close.
 */
export function agentDirName(agentId: string): string {
  const safe = agentId.replace(/[^a-zA-Z0-9_-]/g, "-").slice(0, 64);
  return /[a-zA-Z0-9]/.test(safe) ? safe : "unnamed-agent";
}

/**
 * Written fresh at the start of every turn, from configuration the agent cannot reach.
 *
 * A turn that rewrites `config.toml` to repoint `base_url` at a host it controls captures the full
 * context and the credential of every later turn, and that write lands outside any shadow, so
 * nothing in the file transaction sees it. Regenerating the file each turn means a poisoned copy
 * has a lifetime of zero turns.
 */
export function renderCodexConfig(input: { model: string; baseUrl: string }): string {
  return [
    "# Generated by Shadow Commit at the start of this turn. Edit configuration, not this file.",
    "model = " + JSON.stringify(input.model || "ep-not-configured"),
    'model_provider = "volcengine_ark"',
    "",
    "[model_providers.volcengine_ark]",
    'name = "Volcengine Ark"',
    "base_url = " + JSON.stringify(input.baseUrl),
    'env_key = "ARK_API_KEY"',
    'wire_api = "responses"',
    "requires_openai_auth = false",
    "",
  ].join("\n");
}

export class CodexHomeManager {
  constructor(private readonly config: AppConfig) {}

  /** One directory per agent. A shared one makes restore unsafe under concurrency on its own. */
  dirFor(agentId: string): string {
    if (!this.config.shadowCodexHomePerAgent) return this.config.codexHome;
    return path.join(this.config.codexHome, agentDirName(agentId));
  }

  async prepare(agentId: string, baseUrl: string): Promise<string> {
    const dir = this.dirFor(agentId);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(
      path.join(dir, "config.toml"),
      renderCodexConfig({ model: this.config.arkModel, baseUrl }),
      { encoding: "utf8", mode: 0o600 },
    );
    return dir;
  }

  /** Two copies: the one the turn writes, and the one the restore reads. */
  async seal(agentId: string, shadowDir: string): Promise<SealedCodexHome> {
    const realPath = this.dirFor(agentId);
    const base = path.join(shadowDir, "codex-home");
    const livePath = path.join(base, "live");
    const prePath = path.join(base, "pre");
    await fs.mkdir(livePath, { recursive: true });
    await fs.mkdir(prePath, { recursive: true });
    await execFileAsync("cp", ["-a", realPath + "/.", livePath]);
    await execFileAsync("cp", ["-a", realPath + "/.", prePath]);
    const signature = await this.signature(realPath);
    return {
      agentId,
      realPath,
      livePath,
      prePath,
      preDigest: signature.digest,
      preFiles: signature.files,
    };
  }

  /** Commit: what the turn did to its own memory becomes real, in the same decision as the files. */
  async promote(sealed: SealedCodexHome): Promise<CodexHomeDiff> {
    const diff = await this.diff(sealed.prePath, sealed.livePath);
    const staging = sealed.realPath + ".next-" + crypto.randomBytes(4).toString("hex");
    const retired = sealed.realPath + ".old-" + crypto.randomBytes(4).toString("hex");
    await execFileAsync("cp", ["-a", sealed.livePath, staging]);
    await fs.rename(sealed.realPath, retired);
    try {
      await fs.rename(staging, sealed.realPath);
    } catch (error) {
      await fs.rename(retired, sealed.realPath).catch(() => undefined);
      await fs.rm(staging, { recursive: true, force: true }).catch(() => undefined);
      throw error;
    }
    await fs.rm(retired, { recursive: true, force: true }).catch(() => undefined);
    return diff;
  }

  /**
   * Any verdict that is not commit. The turn never held the real directory, so the expected case
   * is that it is already byte-for-byte what it was; the restore runs anyway, and the journal
   * records whether it was needed, because a silent assumption is not an invariant.
   */
  async restore(sealed: SealedCodexHome): Promise<{ verified: boolean; restored: boolean }> {
    const after = await this.signature(sealed.realPath);
    if (after.digest === sealed.preDigest) return { verified: true, restored: false };
    const staging = sealed.realPath + ".restore-" + crypto.randomBytes(4).toString("hex");
    await execFileAsync("cp", ["-a", sealed.prePath, staging]);
    await fs.rm(sealed.realPath, { recursive: true, force: true });
    await fs.rename(staging, sealed.realPath);
    return { verified: false, restored: true };
  }

  /**
   * What the caller may keep as the agent's thread id.
   *
   * On the first turn Codex mints a new thread; if that turn does not commit, storing the id hands
   * the next turn a conversation whose files were rolled back. On a resume Codex returns the SAME
   * id, so gating the id alone would do nothing from turn two onwards, which is why the snapshot is
   * the mechanism and this is only the first-turn half. One rule covers both: a turn that did not
   * commit reports the thread id the turn started from.
   */
  gateThreadId(
    preTurnThreadId: string | null,
    resultThreadId: string | null,
    decision: "commit" | "discard" | "review" | "conflict",
  ): string | null {
    return decision === "commit" ? resultThreadId : preTurnThreadId;
  }

  /** size:mtime:mode per file, hashed to one value, so a change anywhere in the unit shows up. */
  async signature(dir: string): Promise<{ digest: string; files: number }> {
    const parts: string[] = [];
    const walk = async (current: string, prefix: string): Promise<void> => {
      let entries;
      try {
        entries = await fs.readdir(current, { withFileTypes: true });
      } catch {
        return;
      }
      for (const entry of sortByNameForDigest(entries)) {
        const rel = prefix ? prefix + "/" + entry.name : entry.name;
        const full = path.join(current, entry.name);
        if (entry.isDirectory()) {
          await walk(full, rel);
          continue;
        }
        const stat = await fs.lstat(full).catch(() => null);
        if (stat) parts.push(rel + "|" + stat.size + "|" + stat.mtimeMs + "|" + stat.mode);
      }
    };
    await walk(dir, "");
    return {
      digest: crypto.createHash("sha256").update(parts.join("\n")).digest("hex"),
      files: parts.length,
    };
  }

  /** What the turn did to its own memory, in the shape the journal carries: names and counts. */
  async diff(beforeDir: string, afterDir: string): Promise<CodexHomeDiff> {
    const before = await this.fileMap(beforeDir);
    const after = await this.fileMap(afterDir);
    const added: string[] = [];
    const modified: string[] = [];
    const removed: string[] = [];
    for (const [rel, signature] of after) {
      const previous = before.get(rel);
      if (previous === undefined) added.push(rel);
      else if (previous !== signature) modified.push(rel);
    }
    for (const rel of before.keys()) if (!after.has(rel)) removed.push(rel);
    const changed = added.length + modified.length + removed.length;
    const truncated =
      added.length > DIFF_LIST_LIMIT ||
      modified.length > DIFF_LIST_LIMIT ||
      removed.length > DIFF_LIST_LIMIT;
    return {
      added: added.slice(0, DIFF_LIST_LIMIT),
      modified: modified.slice(0, DIFF_LIST_LIMIT),
      removed: removed.slice(0, DIFF_LIST_LIMIT),
      changed,
      truncated,
    };
  }

  private async fileMap(dir: string): Promise<Map<string, string>> {
    const out = new Map<string, string>();
    const walk = async (current: string, prefix: string): Promise<void> => {
      let entries;
      try {
        entries = await fs.readdir(current, { withFileTypes: true });
      } catch {
        return;
      }
      for (const entry of entries) {
        const rel = prefix ? prefix + "/" + entry.name : entry.name;
        const full = path.join(current, entry.name);
        if (entry.isDirectory()) {
          await walk(full, rel);
          continue;
        }
        const stat = await fs.lstat(full).catch(() => null);
        if (stat) out.set(rel, stat.size + ":" + stat.mode);
      }
    };
    await walk(dir, "");
    return out;
  }
}
