import { describe, expect, it } from "vitest";
import { collapseKeyValues, normaliseText } from "./normalise.js";

/**
 * The lines of `normalise.ts` a deletion probe could remove with the whole rule layer green.
 *
 * 44 deletable lines, 14 survivors. Twelve are rows of the confusable table, five mappings to a
 * row, and two are the `"g"` flag on the two assignment patterns.
 *
 * The confusable rows are the awkward case. Reading the table to assert the table would pass
 * whatever the table said, so each row below is reached through a WORD, and the expected spelling is
 * what the glyph renders as to a reader, written by hand rather than copied out of the map. One
 * character per row, chosen so a row's removal breaks its own line and no other.
 *
 * WHAT THIS FILE DOES NOT ESTABLISH. One character per row is not the row: four of the five
 * mappings in each row stay undefended, and the table is generated by
 * `scripts/generate-unicode-confusables.mjs`, so the honest gate for the rest is a check against
 * that generator's output rather than more hand-written rows here. That gap is reported.
 */

describe("a lookalike letter folds onto the letter it renders as", () => {
  /** [what an attacker writes, what a reader sees, which script the lookalike comes from] */
  const SPELLINGS: ReadonlyArray<readonly [string, string, string]> = [
    ["сurl", "curl", "Cyrillic es"],
    ["pasѕword", "password", "Cyrillic dze"],
    ["ԁecode", "decode", "Cyrillic komi de"],
    ["АWS", "AWS", "Cyrillic A"],
    ["ОK", "OK", "Cyrillic O"],
    ["УES", "YES", "Cyrillic U"],
    ["level З", "level 3", "Cyrillic Ze"],
    ["eχec", "exec", "Greek chi"],
    ["ΕVAL", "EVAL", "Greek Epsilon"],
    ["ΚEY", "KEY", "Greek Kappa"],
    ["ΡASS", "PASS", "Greek Rho"],
    ["tօken", "token", "Armenian oh"],
  ];

  it.each(SPELLINGS)("reads %s as %s (%s)", (written, rendered) => {
    expect(normaliseText(written)).toBe(rendered);
  });
});

describe("every assignment on a line is collapsed, not only the first", () => {
  it("collapses a second quoted pair on the same line", () => {
    expect(collapseKeyValues('{ "host": "db.internal", "password": "hunter2hunter2" }'))
      .toContain("password=hunter2hunter2");
  });

  it("collapses a second bare pair on the same line", () => {
    expect(collapseKeyValues("host: db.internal, password: hunter2hunter2"))
      .toContain("password=hunter2hunter2");
  });
});
